version: '3'
services:
  imup:
    build: .
    # volumes:
    #   - ./build/upload:/data:rw
    # user: "1000:1000"
    user: "nobody:nobody"
    ports:
      - "3000:3003/tcp"
    command: ["imup", "-listen", "0.0.0.0:3003", "-swagurl", "http://localhost:3000/swagger"]
    # command: ["imup", "-listen", "0.0.0.0:3003", "-swagurl", "http://example.com/swagger"]